### ISSUE TITLE
renamed and obfuscated dynCalls

### ISSUE THREAD

**Issue by vc4d-5x2** [nneonneo/ghidra-wasm-plugin#14]
I use ghidra 10.2.2 with the 2.1.0 version of this plugin.
Recently a unity webgl game I know has obfuscated their dyncalls so that the current analyze_dyncalls.py script of this plugin does not work on it. I have tried to investigate a little bit of what exactly they are doing but don't know how to make it work.
The script crashes with an `OverflowError: range() result has too many items`. I think I know why this happens but will explain it later. 
Attached here are compressed versions of the new obfuscated version of the wasm, the framework.js for this obfuscated wasm, an old version that did not do this and works as expected and a python script to rename the obscured dynCalls to their correct names according to the framework.js. 
[new_framework.js.gz](https://github.com/nneonneo/ghidra-wasm-plugin/files/10563230/new_framework.js.gz)
[new_notworking.wasm.gz](https://github.com/nneonneo/ghidra-wasm-plugin/files/10563231/new_notworking.wasm.gz)
[old_working.wasm.gz](https://github.com/nneonneo/ghidra-wasm-plugin/files/10563232/old_working.wasm.gz)
[rename_dyncalls.py.gz](https://github.com/nneonneo/ghidra-wasm-plugin/files/10563233/rename_dyncalls.py.gz)

They have renamed the individual dyncalls to 2 letter names like "jj" and have changed the framework.js to accomodate that.
```js
var dynCall_jiji = Module['dynCall_jiji'] = function () {
  return (dynCall_jiji = Module['dynCall_jiji'] = Module['asm']['jj']).apply(null, arguments)
};
```
The imports are also renamed but in my testing this did not make any difference even if I renamed them so they are possibly irrelevant.

The error of the script happens in the renameDyncalls function because the mask value in the range is always 0xffffffff. I have checked this by printing the values of all dyncalls inside your script and every single one has offset=0 and mask=0xffffffff.
When I tried to investigate this I noticed that almost every single dyncall I checked in the new version only consisted of 
```wasm
local.get l1
local.get l2
[possibly more local.get]
call_indirect
```
unlike the old version where almost every single dyncall had either one or more of i32.const, i32.add, i32.and the analyze_dyncall script checks for. I think this is the reason why offset is always 0 and mask is always 0xffffffff.

I have not been able to find any framework or program for unity that possibly creates this result and I have absolutely no Idea on how to proceed with this. Maybe there is more going but that is everything I have been able to figure out.

**Comment by nneonneo** [comment]
Thanks for the report. It looks like the "obfuscation" might just be part of a newer Unity build process (as of ~this month, [per reports online](https://forum.unity.com/threads/defining-a-function-with-a-two-letter-name-in-a-jslib-may-result-in-runtime-error.1391068/)?). Luckily, framework.js isn't obfuscated, so it should be easy to recover the original names from `asmLibraryArg` and statements like`Module['dynCall_jiji'] = Module['asm']['jj']`. It would probably be possible to make a separate script to extract these automatically and apply them to the Ghidra database, although I'm not sure if that script would be appropriate for this repo as it might be specific to Unity.

I guess it's possible that the dynCall implementation changed at the same time as the Unity changes. Actually, it looks a lot simpler - I don't even think `analyze_dyncalls.py` is necessary now. In Wasm, function "pointers" are integer indices into the function table. Previously, these indices were namespaced by the function type. For example, call type `jiji` index 1 would be a different function than call type `jjji` index 1; that is, if you have a function pointer with the value 1, which function it actually refers to would depend on the actual type of the function pointer. Since the IL2CPP metadata refers to these indices, it was necessary to use `analyze_dyncalls` to sort out the (type, index) -> function mapping, then use type information + function index numbers + function names from IL2CPP metadata to rename and type the WASM functions.

However, it *looks like* the new way is to simply use the table indices directly as the function pointer values, without namespacing. This is way simpler: we don't need the type information to resolve which function a given index refers to, so we should be able to do away with the dyncall function parsing and the type signature matching in IL2CPP tooling. 

The other benefit is that this should make it possible to resolve function pointers in RAM into function references. Previously this could not be done without analyzing the call site, which would often be infeasible (due to indirection); now, as long as you can identify it as a function pointer, you immediately know which function it is.

If this is an Emscripten-wide change, I hope it sticks - it'll make reversing a lot more pleasant!

**Comment by nneonneo** [comment]
analyze_dyncalls should be considered specific to the “namespaced” mask+offset implementations of dyncall. If the dyncall functions aren’t doing mask+offset, and the function pointer indices are just actual table indices, then there is no need for analyze_dyncalls at all. Concretely, it might be nice to document the situations in which analyze_dyncalls is necessary, possibly with reference to the configuration of emscripten or llvm that generates the namespaced dyncall functions. That will help future reversers decide whether to run the script. On Feb 2, 2023, at 11:22 PM, vc4d-5x2 ***@***.***> wrote:﻿
The newer example I gave you is actually multiple months old so this renaming has existed for at least a few months. Also I assumed this to be some type of obfuscation because some versions after the new version I gave you did not have this, so I just assumed this could not be the default behaviour of Unity.
I agree that renaming the dyncalls should not be a script for this plugin but something more unity specific.
Il2CppDumper has support for your wasm plugin but currently depends on the functionality of analyze_dyncalls to correctly rename functions. Could/Should analyze_dyncalls be changed to work like before or is this something the author of Il2CppDumper should fix? If there is no reason to change analyze_dyncalls please feel free to close the issue and I will report it to Il2CppDumper.

**Comment by nneonneo** [comment]
Thanks for the additional context.

If I understand correctly, Il2CppDumper is making use of the function name pattern "func_<type>_<index>" for renaming. For example, if the metadata specifies the function "foo(int i, int j)" with 'address' 34, then it will rename "func_ii_34" to "foo".

We can do something similar with the flat namespace. I think it will suffice to rename by using the index alone, e.g. `func_<index>`, because the type information will not be necessary to resolve the index into a function. Indeed, we can use something as simple as the following script:

```python
from __future__ import print_function
from wasm.analysis import WasmAnalysis
from ghidra.program.model.symbol import SourceType

progspace = currentProgram.addressFactory.getAddressSpace("ram")
tablespace = currentProgram.addressFactory.getAddressSpace("table")
dynCallNamespace = currentProgram.symbolTable.getOrCreateNameSpace(currentProgram.globalNamespace, "dynCall", SourceType.USER_DEFINED)

def getTableFunction(offset):
    funcAddr = getInt(tablespace.getAddress(offset * 4)) & 0xffffffff
    return getFunctionAt(progspace.getAddress(funcAddr))

count = WasmAnalysis.getState(currentProgram).module.nonImportedTables[0].limits.initial
for i in range(1, count):
    func = getTableFunction(i)
    if func:
        name = "func_%d" % i
        if func.name.startswith("unnamed_function_"):
            func.setName(name, SourceType.ANALYSIS)
        currentProgram.symbolTable.createLabel(func.entryPoint, name, dynCallNamespace, SourceType.USER_DEFINED)
```

I'll be adding this to the repo if it works. It will still require downstream changes: Il2CppDumper will need to be modified to work with the new function names and the new interpretation of function indices. This script will handle the renaming from the Wasm side.
