### ISSUE TITLE
Adaption to LEB128 required since upstream 0e45354

### ISSUE THREAD

**Issue by jobermayr** [nneonneo/ghidra-wasm-plugin#15]
Since https://github.com/NationalSecurityAgency/ghidra/commit/0e45354 it isn't possible to build.

**Comment by nneonneo** [comment]
It looks like we can mostly replace our uses of LEB128 with LEB128Info, but there's potentially a bit more work to do for the parts that can be part of a DataType (since there's new `ghidra.program.model.data.[Un]SignedLeb128DataType` classes). I'm inclined to wait until they actually release e.g. Ghidra 10.3 incorporating this change.

**Comment by jobermayr** [comment]
> I'm inclined to wait until they actually release e.g. Ghidra 10.3 incorporating this change.

Then I have to wait for reinclusion to [ghidra-staging](https://github.com/jobermayr/ghidra-staging). You can find "upstream" pull request 4103 there temporary in bad.

**Comment by nneonneo** [comment]
@jobermayr I updated [nneonneo/wasm](https://github.com/nneonneo/ghidra/tree/wasm) with the necessary changes to compile with the Ghidra master branch as of today. Please give that a whirl and let me know if it works for you.

It sounds like this plugin will be moving for inclusion in a future Ghidra release. Depending on which release it makes it into, I may or may not update this repository with a patch.

**Comment by nneonneo** [comment]
Fixed in 017bbb1eb982551038ffab3dc179ed3619a9ca27.
